// <auto-generated />
using HRMSDotNetCoreMiniProject.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HRMSDotNetCoreMiniProject.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250714054041_createtable")]
    partial class createtable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HRMSDotNetCoreMiniProject.Models.Department", b =>
                {
                    b.Property<int>("deptid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("deptid"));

                    b.Property<string>("deptname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("deptstatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("deptid");

                    b.ToTable("departments");
                });

            modelBuilder.Entity("HRMSDotNetCoreMiniProject.Models.Employee", b =>
                {
                    b.Property<int>("empid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("empid"));

                    b.Property<int>("deptid")
                        .HasColumnType("int");

                    b.Property<string>("empemail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("empname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("empsalary")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("empstatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("mgrid")
                        .HasColumnType("int");

                    b.HasKey("empid");

                    b.HasIndex("deptid");

                    b.HasIndex("mgrid");

                    b.ToTable("employees");
                });

            modelBuilder.Entity("HRMSDotNetCoreMiniProject.Models.Manager", b =>
                {
                    b.Property<int>("mgrid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("mgrid"));

                    b.Property<int>("deptsdeptid")
                        .HasColumnType("int");

                    b.Property<string>("mgrname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("mgrstatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("mgrid");

                    b.HasIndex("deptsdeptid");

                    b.ToTable("managers");
                });

            modelBuilder.Entity("HRMSDotNetCoreMiniProject.Models.UserDetails", b =>
                {
                    b.Property<int>("userid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("userid"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("userrole")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("userid");

                    b.ToTable("userdetails");
                });

            modelBuilder.Entity("HRMSDotNetCoreMiniProject.Models.Employee", b =>
                {
                    b.HasOne("HRMSDotNetCoreMiniProject.Models.Department", "department")
                        .WithMany("emplist")
                        .HasForeignKey("deptid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HRMSDotNetCoreMiniProject.Models.Manager", "manager")
                        .WithMany("emps")
                        .HasForeignKey("mgrid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("department");

                    b.Navigation("manager");
                });

            modelBuilder.Entity("HRMSDotNetCoreMiniProject.Models.Manager", b =>
                {
                    b.HasOne("HRMSDotNetCoreMiniProject.Models.Department", "depts")
                        .WithMany()
                        .HasForeignKey("deptsdeptid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("depts");
                });

            modelBuilder.Entity("HRMSDotNetCoreMiniProject.Models.Department", b =>
                {
                    b.Navigation("emplist");
                });

            modelBuilder.Entity("HRMSDotNetCoreMiniProject.Models.Manager", b =>
                {
                    b.Navigation("emps");
                });
#pragma warning restore 612, 618
        }
    }
}
